spring.application.name=reservation
spring.datasource.url=jdbc:postgresql://ep-tiny-paper-b4cs9vfj-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YHUVR5d8bnfO
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
app.admin-token=${APP_ADMIN_TOKEN:local-dev-admin-token}